[theme]
primaryColor="#007bff"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

# For dark theme (if Streamlit auto-detects or user selects)
# You would define a corresponding dark theme palette here.
# Streamlit handles switching these variables.
